"""
    Fitbit Web API

    Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/oauth2/#obtaining-consent.  # noqa: E501

    OpenAPI spec version: 1

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import fitbit
from fitbit.api.heart_rate_intraday_time_series_api import (  # noqa: E501
    HeartRateIntradayTimeSeriesApi,
)
from fitbit.rest import ApiException


class TestHeartRateIntradayTimeSeriesApi(unittest.TestCase):
    """HeartRateIntradayTimeSeriesApi unit test stubs"""

    def setUp(self):
        self.api = HeartRateIntradayTimeSeriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_heart_by_date_intraday(self):
        """Test case for get_heart_by_date_intraday

        Get Heart Rate Intraday Time Series  # noqa: E501
        """
        pass

    def test_get_heart_by_date_range_intraday(self):
        """Test case for get_heart_by_date_range_intraday

        Get Heart Rate Intraday Time Series  # noqa: E501
        """
        pass

    def test_get_heart_by_date_range_timestamp_intraday(self):
        """Test case for get_heart_by_date_range_timestamp_intraday

        Get Heart Rate Intraday Time Series  # noqa: E501
        """
        pass

    def test_get_heart_by_date_timestamp_intraday(self):
        """Test case for get_heart_by_date_timestamp_intraday

        Get Heart Rate Intraday Time Series  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
