"""
    Fitbit Web API

    Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/oauth2/#obtaining-consent.  # noqa: E501

    OpenAPI spec version: 1

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import fitbit
from fitbit.api.activity_api import ActivityApi  # noqa: E501
from fitbit.rest import ApiException


class TestActivityApi(unittest.TestCase):
    """ActivityApi unit test stubs"""

    def setUp(self):
        self.api = ActivityApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_activities_log(self):
        """Test case for add_activities_log

        Log Activity  # noqa: E501
        """
        pass

    def test_add_favorite_activities(self):
        """Test case for add_favorite_activities

        Add Favorite Activity  # noqa: E501
        """
        pass

    def test_add_update_activities_goals(self):
        """Test case for add_update_activities_goals

        Update Activity Goals  # noqa: E501
        """
        pass

    def test_delete_activities_log(self):
        """Test case for delete_activities_log

        Delete Activity Log  # noqa: E501
        """
        pass

    def test_delete_favorite_activities(self):
        """Test case for delete_favorite_activities

        Delete Favorite Activity  # noqa: E501
        """
        pass

    def test_get_activities_by_date(self):
        """Test case for get_activities_by_date

        Get Activity Summary by Date   # noqa: E501
        """
        pass

    def test_get_activities_goals(self):
        """Test case for get_activities_goals

        Get Activity Goals  # noqa: E501
        """
        pass

    def test_get_activities_log(self):
        """Test case for get_activities_log

        Get Lifetime Stats  # noqa: E501
        """
        pass

    def test_get_activities_log_list(self):
        """Test case for get_activities_log_list

        Get Activity Log List  # noqa: E501
        """
        pass

    def test_get_activities_tcx(self):
        """Test case for get_activities_tcx

        Get Activity TCX  # noqa: E501
        """
        pass

    def test_get_activities_type_detail(self):
        """Test case for get_activities_type_detail

        Get Activity Type  # noqa: E501
        """
        pass

    def test_get_activities_types(self):
        """Test case for get_activities_types

        Browse Activity Types  # noqa: E501
        """
        pass

    def test_get_favorite_activities(self):
        """Test case for get_favorite_activities

        Get Favorite Activities  # noqa: E501
        """
        pass

    def test_get_frequent_activities(self):
        """Test case for get_frequent_activities

        Get Frequent Activities  # noqa: E501
        """
        pass

    def test_get_recent_activities(self):
        """Test case for get_recent_activities

        Get Recent Activity Types  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
