"""
    Fitbit Web API

    Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/oauth2/#obtaining-consent.  # noqa: E501

    OpenAPI spec version: 1

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import fitbit
from fitbit.api.sleep_api import SleepApi  # noqa: E501
from fitbit.rest import ApiException


class TestSleepApi(unittest.TestCase):
    """SleepApi unit test stubs"""

    def setUp(self):
        self.api = SleepApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_sleep(self):
        """Test case for add_sleep

        Log Sleep  # noqa: E501
        """
        pass

    def test_delete_sleep(self):
        """Test case for delete_sleep

        Delete Sleep Log  # noqa: E501
        """
        pass

    def test_get_sleep_by_date(self):
        """Test case for get_sleep_by_date

        Get Sleep Log  # noqa: E501
        """
        pass

    def test_get_sleep_by_date_range(self):
        """Test case for get_sleep_by_date_range

        Get Sleep Logs by Date Range  # noqa: E501
        """
        pass

    def test_get_sleep_goal(self):
        """Test case for get_sleep_goal

        Get Sleep Goal  # noqa: E501
        """
        pass

    def test_get_sleep_list(self):
        """Test case for get_sleep_list

        Get Sleep Logs List  # noqa: E501
        """
        pass

    def test_update_sleep_goal(self):
        """Test case for update_sleep_goal

        Update Sleep Goal  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
