"""
    Fitbit Web API

    Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/oauth2/#obtaining-consent.  # noqa: E501

    OpenAPI spec version: 1

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import fitbit
from fitbit.api.body_and_weight_api import BodyAndWeightApi  # noqa: E501
from fitbit.rest import ApiException


class TestBodyAndWeightApi(unittest.TestCase):
    """BodyAndWeightApi unit test stubs"""

    def setUp(self):
        self.api = BodyAndWeightApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_body_fat_log(self):
        """Test case for add_body_fat_log

        Log Body Fat  # noqa: E501
        """
        pass

    def test_add_weight_log(self):
        """Test case for add_weight_log

        Log Weight  # noqa: E501
        """
        pass

    def test_delete_body_fat_log(self):
        """Test case for delete_body_fat_log

        Delete Body Fat Log  # noqa: E501
        """
        pass

    def test_delete_weight_log(self):
        """Test case for delete_weight_log

        Delete Weight Log  # noqa: E501
        """
        pass

    def test_get_body_fat_by_date(self):
        """Test case for get_body_fat_by_date

        Get Body Fat Logs  # noqa: E501
        """
        pass

    def test_get_body_fat_by_date_period(self):
        """Test case for get_body_fat_by_date_period

        Get Body Fat Logs  # noqa: E501
        """
        pass

    def test_get_body_fat_by_date_range(self):
        """Test case for get_body_fat_by_date_range

        Get Body Fat Logs  # noqa: E501
        """
        pass

    def test_get_body_goals(self):
        """Test case for get_body_goals

        Get Body Goals  # noqa: E501
        """
        pass

    def test_get_weight_by_date(self):
        """Test case for get_weight_by_date

        Get Weight Logs  # noqa: E501
        """
        pass

    def test_get_weight_by_date_period(self):
        """Test case for get_weight_by_date_period

        Get Body Fat Logs  # noqa: E501
        """
        pass

    def test_get_weight_by_date_range(self):
        """Test case for get_weight_by_date_range

        Get Body Fat Logs  # noqa: E501
        """
        pass

    def test_update_body_fat_goal(self):
        """Test case for update_body_fat_goal

        Update Body Fat Goal  # noqa: E501
        """
        pass

    def test_update_weight_goal(self):
        """Test case for update_weight_goal

        Update Weight Goal  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
