"""
    Fitbit Web API

    Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/oauth2/#obtaining-consent.  # noqa: E501

    OpenAPI spec version: 1

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import fitbit
from fitbit.api.devices_api import DevicesApi  # noqa: E501
from fitbit.rest import ApiException


class TestDevicesApi(unittest.TestCase):
    """DevicesApi unit test stubs"""

    def setUp(self):
        self.api = DevicesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_alarms(self):
        """Test case for add_alarms

        Add Alarm  # noqa: E501
        """
        pass

    def test_delete_alarms(self):
        """Test case for delete_alarms

        Delete Alarm  # noqa: E501
        """
        pass

    def test_get_alarms(self):
        """Test case for get_alarms

        Get Alarms  # noqa: E501
        """
        pass

    def test_get_devices(self):
        """Test case for get_devices

        Get Devices  # noqa: E501
        """
        pass

    def test_update_alarms(self):
        """Test case for update_alarms

        Update Alarm  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
