"""
    Fitbit Web API

    Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/oauth2/#obtaining-consent.  # noqa: E501

    OpenAPI spec version: 1

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import fitbit
from fitbit.api.food_and_water_api import FoodAndWaterApi  # noqa: E501
from fitbit.rest import ApiException


class TestFoodAndWaterApi(unittest.TestCase):
    """FoodAndWaterApi unit test stubs"""

    def setUp(self):
        self.api = FoodAndWaterApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_favorite_food(self):
        """Test case for add_favorite_food

        Add Favorite Food  # noqa: E501
        """
        pass

    def test_add_foods(self):
        """Test case for add_foods

        Create Food  # noqa: E501
        """
        pass

    def test_add_foods_log(self):
        """Test case for add_foods_log

        Log Food  # noqa: E501
        """
        pass

    def test_add_meal(self):
        """Test case for add_meal

        Create Meal  # noqa: E501
        """
        pass

    def test_add_update_foods_goal(self):
        """Test case for add_update_foods_goal

        Update Food Goal  # noqa: E501
        """
        pass

    def test_add_update_water_goal(self):
        """Test case for add_update_water_goal

        Update Water Goal  # noqa: E501
        """
        pass

    def test_add_water_log(self):
        """Test case for add_water_log

        Log Water  # noqa: E501
        """
        pass

    def test_delete_favorite_food(self):
        """Test case for delete_favorite_food

        Delete Favorite Food  # noqa: E501
        """
        pass

    def test_delete_foods(self):
        """Test case for delete_foods

        Delete Custom Food  # noqa: E501
        """
        pass

    def test_delete_foods_log(self):
        """Test case for delete_foods_log

        Delete Food Log  # noqa: E501
        """
        pass

    def test_delete_meal(self):
        """Test case for delete_meal

        Delete Meal  # noqa: E501
        """
        pass

    def test_delete_water_log(self):
        """Test case for delete_water_log

        Delete Water Log  # noqa: E501
        """
        pass

    def test_edit_foods_log(self):
        """Test case for edit_foods_log

        Edit Food Log  # noqa: E501
        """
        pass

    def test_get_favorite_foods(self):
        """Test case for get_favorite_foods

        Get Favorite Foods  # noqa: E501
        """
        pass

    def test_get_foods_by_date(self):
        """Test case for get_foods_by_date

        Get Food Logs  # noqa: E501
        """
        pass

    def test_get_foods_goal(self):
        """Test case for get_foods_goal

        Get Food Goals  # noqa: E501
        """
        pass

    def test_get_foods_info(self):
        """Test case for get_foods_info

        Get Food  # noqa: E501
        """
        pass

    def test_get_foods_list(self):
        """Test case for get_foods_list

        Search Foods  # noqa: E501
        """
        pass

    def test_get_foods_locales(self):
        """Test case for get_foods_locales

        Get Food Locales  # noqa: E501
        """
        pass

    def test_get_foods_units(self):
        """Test case for get_foods_units

        Get Food Units  # noqa: E501
        """
        pass

    def test_get_frequent_foods(self):
        """Test case for get_frequent_foods

        Get Frequent Foods  # noqa: E501
        """
        pass

    def test_get_meals(self):
        """Test case for get_meals

        Get Meals  # noqa: E501
        """
        pass

    def test_get_recent_foods(self):
        """Test case for get_recent_foods

        Get Recent Foods  # noqa: E501
        """
        pass

    def test_get_water_by_date(self):
        """Test case for get_water_by_date

        Get Water Logs  # noqa: E501
        """
        pass

    def test_get_water_goal(self):
        """Test case for get_water_goal

        Get Water Goal  # noqa: E501
        """
        pass

    def test_update_meal(self):
        """Test case for update_meal

        Edit Meal  # noqa: E501
        """
        pass

    def test_update_water_log(self):
        """Test case for update_water_log

        Update Water Log  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
