"""
    Fitbit Web API

    Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Authorization header to each request with an access token obtained using the steps outlined here: https://dev.fitbit.com/build/reference/web-api/oauth2/#obtaining-consent.  # noqa: E501

    OpenAPI spec version: 1

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import fitbit
from fitbit.api.friends_api import FriendsApi  # noqa: E501
from fitbit.rest import ApiException


class TestFriendsApi(unittest.TestCase):
    """FriendsApi unit test stubs"""

    def setUp(self):
        self.api = FriendsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_friends_invitations(self):
        """Test case for create_friends_invitations

        Invite Friends  # noqa: E501
        """
        pass

    def test_get_friends(self):
        """Test case for get_friends

        Get Friends  # noqa: E501
        """
        pass

    def test_get_friends_invitations(self):
        """Test case for get_friends_invitations

        Get Friend Invitations  # noqa: E501
        """
        pass

    def test_get_friends_leaderboard(self):
        """Test case for get_friends_leaderboard

        Get Friends Leaderboard  # noqa: E501
        """
        pass

    def test_respond_friends_invitation(self):
        """Test case for respond_friends_invitation

        Respond to Friend Invitation  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
